import {plants,pots,lights,difficulties,sizes,questions,sizeOrder,sizePreferenceValues,plantTypes,filterPlants,plantGeometry} from './data.js';
import {getPlantMatch,rankPlants} from './recommendation.js';
import {read,write,fresh} from './storage.js';
import {rooms,chooseRoom,roomImageData} from './rooms.js';
import {analyzeImage} from './analysis.js';
let state=read(),question=0,answers={},spaceType='거실',pendingName='',editAnalysis=false,tab='plants',plantGroup='all',potColor='',potMaterial='',viz=null,toastTimer;
let introIndex=0,splashVisible=true;
let careDestination='/',photoBusy=false,analysisJob=null,analysisError='',analysisController=null,lastRoute='';
const activeSpace=()=>state.spaces.find(s=>s.id===state.activeSpaceId)||null;
const uploadSpace=()=>state.pendingSpace?null:activeSpace();
const newId=()=>crypto.randomUUID?.()||('id-'+Date.now()+'-'+Math.random().toString(36).slice(2));
const app=document.querySelector('#app');
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const button=(label,action,cls='',attrs='')=>`<button class="btn ${cls}" data-action="${action}" ${attrs}>${label}</button>`;
const link=(label,path,cls='btn')=>`<a class="${cls}" href="#${path}">${label}</a>`;
const photo=(space=activeSpace())=>space?.imageDataUrl||(space?.imageSource==='demo'?'assets/demo/room.png':null);
const member=()=>!!(state.signedIn&&state.account&&state.careProfile);
const ready=()=>activeSpace()?.analysisConfirmed&&member();
const match=p=>getPlantMatch(p,activeSpace(),member()?state.careProfile:null);
const ranked=()=>rankPlants(plants,activeSpace(),member()?state.careProfile:null);
const find=id=>plants.find(p=>p.id===id);
function toast(s){const e=document.querySelector('#toast');e.textContent=s;e.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>e.classList.remove('show'),2800);}
function commit(next){try{write(next);state=next;return true;}catch{toast('저장하지 못했어요. 저장 공간을 확인해주세요.');return false;}}
function go(path){if(location.hash==='#'+path)render();else location.hash=path;}
const icons={home:'<path d="m3 10 9-7 9 7v11h-6v-7H9v7H3z"/>',explore:'<circle cx="12" cy="12" r="9"/><path d="m16 8-3 5-5 3 3-5z"/>',saved:'<path d="M20 5c-3-3-6-1-8 1-2-2-5-4-8-1-4 4 2 10 8 15 6-5 12-11 8-15z"/>',space:'<rect x="4" y="3" width="16" height="18" rx="2"/><path d="M4 9h16M10 9v12"/>'};
function nav(route){return `<nav class="nav" aria-label="주 메뉴">${[['/','홈','home'],['/explore','탐색','explore'],['/saved','저장','saved'],['/my-page','마이페이지','space']].map(([path,label,icon])=>`<a href="#${path}" class="${route===path?'active':''}"><svg viewBox="0 0 24 24" aria-hidden="true">${icons[icon]}</svg>${label}</a>`).join('')}</nav>`;}
function empty(title,description,cta='식물 탐색하기',path='/explore'){return `<div class="empty"><h2>${title}</h2><p>${description}</p>${link(cta,path,'btn secondary wide')}</div>`;}
function plantCard(p){const m=match(p);return `<article class="card"><div class="cardtop"><a href="#/plants/${p.id}"><img src="${p.image}" alt="${p.name}" loading="lazy"></a><button class="icon ${state.savedPlantIds.includes(p.id)?'active':''}" aria-label="${p.name} ${state.savedPlantIds.includes(p.id)?'저장 취소':'저장'}" aria-pressed="${state.savedPlantIds.includes(p.id)}" data-action="save:${p.id}">${state.savedPlantIds.includes(p.id)?'♥':'♡'}</button></div><div class="cardbody"><div class="row"><h3>${p.name}</h3>${m?`<span class="score">${m.score}<small>점</small></span>`:''}</div><small>${p.english}</small><div class="meta">${difficulties[p.difficulty]} · ${p.sizes.map(i=>sizes[i]).join(' / ')}</div>${m?`<small>입력 조건 기준 적합도</small>${m.reasons.slice(0,2).map(r=>`<div class="reason">✓ ${r}</div>`).join('')}${m.cautions.length?`<div class="warn">△ ${m.cautions[0]}</div>`:''}`:`<p class="reason">${p.description}</p>`}<div class="row" style="margin-top:14px">${link('자세히 보기','/plants/'+p.id,'btn secondary')}${button(state.comparePlantIds.includes(p.id)?'비교 취소':'＋ 비교',`compare:${p.id}`,'text')}</div>${link('내 공간에 놓아보기','/visualizer/'+p.id,'btn wide card-place')}</div></article>`;}
function header(route,title,onboarding){return `<header>${route==='/'?'<a href="#/" class="brand" aria-label="seekgoo 홈"><img src="assets/brand/logo-transparent.png" alt="seekgoo"></a>':`<button class="back" data-action="back" aria-label="뒤로">‹</button><span>${title}</span>`}${route==='/'?'<span class="home-tagline">Find your plant.<br>Meet your 식구.</span>':onboarding&&!['/auth','/space/result'].includes(route)?button('나가기',route==='/profile/care'?'care-exit':'exit','text'):'<span class="header-spacer" aria-hidden="true"></span>'}</header>`;}
function spacePicker(){return state.spaces.length?`<div class="space-picker" aria-label="공간 선택">${state.spaces.map(s=>`<button class="chip ${s.id===state.activeSpaceId?'active':''}" data-action="select-space:${s.id}" aria-pressed="${s.id===state.activeSpaceId}">${escape(s.name)}</button>`).join('')}${state.spaces.length<4?button('＋ 공간','new-space','text'):''}</div>`:'';}
function spaceBlocks(){return `<div class="space-blocks">${state.spaces.map(space=>`<button class="space-block ${space.id===state.activeSpaceId?'active':''}" data-action="select-space:${space.id}" aria-pressed="${space.id===state.activeSpaceId}"><img src="${photo(space)}" alt="${escape(space.name)}"><span>${escape(space.name)}</span><small>${space.analysisConfirmed?lights[space.analysis.light]:'공간 정보 입력'}</small></button>`).join('')}${state.spaces.length<4?'<button class="space-block add-space" data-action="new-space"><span class="plus" aria-hidden="true">＋</span><span>공간 추가하기</span></button>':''}</div>`;}
function home(){const space=activeSpace();return `<span class="tiny">Your little green world</span><h1>초록이 머무는<br>나의 공간</h1>${!space?'<p>식구가 함께할 자리를 하나씩 담아보세요.</p>':''}${spaceBlocks()}${space?`<div class="selected-space"><h2>${escape(space.name)}</h2>${button('이 공간에 놓아보기','space-place:'+space.id,'wide')}${!space.analysisConfirmed?link('공간 정보 확인하기','/space/result','btn secondary wide'):member()?button('이 공간의 추천 식물 보기','recommend','secondary wide'):link('식물 둘러보기','/explore','btn secondary wide')}</div>`:link('먼저 식물 둘러보기 →','/explore','btn text wide')}${ready()?`<div class="sectionhead"><h2>이 공간과 잘 맞는 식물</h2>${link('전체 보기','/recommendations','')}</div><div class="cards compact">${ranked().slice(0,3).map(plantCard).join('')||empty('현재 조건에 맞는 추천 식물이 없어요','공간 정보를 수정하거나 전체 식물을 둘러보세요.','공간 정보 수정','/space/result')}</div>`:''}`;}

function setup(){const meta=state.pendingSpace;if(meta){spaceType=meta.type;pendingName=meta.name;}return `<span class="tiny">My space · ${state.spaces.length+1} / 4</span><h1>식물을 어디에<br>둘 예정인가요?</h1><p>같은 공간도 자리마다 따로 등록할 수 있어요.</p><div class="stack">${['거실','침실','작업실','베란다','기타'].map((v,i)=>`<button class="choice ${spaceType===v?'active':''}" data-action="type:${v}" aria-pressed="${spaceType===v}"><span>${['▱','▰','▤','▥','＋'][i]} &nbsp; ${v}</span><span>${spaceType===v?'✓':''}</span></button>`).join('')}</div><label for="space-name">공간 이름</label><input id="space-name" maxlength="30" placeholder="${spaceType==='기타'?'마당, 정원, 테라스, 현관 앞':'예: '+spaceType+' 창가'}" value="${escape(pendingName)}"><small>직접 이름을 붙여주세요. 비워두면 공간 종류를 이름으로 사용해요.</small>${button('다음 →','setup-next','wide')}`;}
function upload(){const space=uploadSpace(),type=state.pendingSpace?.type||space?.type||spaceType;return `<span class="tiny">Your room / ${escape(type)}</span><h1>식물이 머무를<br>자리를 담아주세요.</h1><p>창문과 식물을 둘 위치가 함께 보이면 좋아요.</p>${photo(space)?`<img class="room" src="${photo(space)}" alt="${escape(space.name)} 공간 사진"><div class="notice">사진을 바꾸면 이 공간에 저장한 조합의 배치가 초기화돼요.</div>`:'<div class="uploadbox"><h2>나의 공간을 담아주세요</h2><p>JPG · PNG · WebP</p></div>'}<input type="file" accept="image/jpeg,image/png,image/webp" id="photo-file" hidden><div class="photo-actions">${button(photo(space)?'사진 교체하기':'사진 선택','choose-photo','secondary',photoBusy?'disabled':'')}${button(photoBusy?'사진 준비 중…':photo(space)?'다시 촬영':'사진 촬영','camera','secondary',photoBusy?'disabled':'')}</div>${type==='기타'?'<small>마당, 정원, 테라스, 현관 앞 풍경을 담을 수 있어요.</small>':''}<p class="photo-privacy">분석을 시작하면 선택한 사진을 채광 확인에 사용해요.</p>${button('이 사진으로 분석하기','analyze','wide',!photo(space)||photoBusy?'disabled':'')}${photo(space)?link('공간 정보 직접 입력하기','/space/result','btn text wide'):''}`;}
function analysis(){const space=activeSpace(),a=space.analysis||{},complete=space.analysisCompleted&&a.source==='vision';return `${complete?'<span class="badge">분석완료!</span>':''}<h1>${complete?'공간을 살펴봤어요.':'공간 정보를<br>알려주세요.'}</h1><p>${complete?'아래는 사진을 기반으로 분석한 정보예요! 실제 공간과 다른 부분이 있나요?':'채광 정보를 선택하면 공간에 맞는 식물을 찾을 수 있어요.'}</p><img class="room" src="${photo()}" alt="${escape(space.name)} 공간 사진">${editAnalysis||!Number.isInteger(a.light)?`<label for="light">채광 *</label><select id="light"><option value="">선택해주세요</option>${lights.map((l,i)=>`<option value="${i}" ${a.light===i?'selected':''}>${l}</option>`).join('')}</select><label for="temperature">온도 (선택, °C)</label><input id="temperature" type="number" min="-20" max="60" step="0.1" placeholder="모름 / 입력 안 함" value="${a.temperatureC??''}">${button('공간 정보 저장','analysis-save','wide')}`:`<div class="metrics"><div class="metric"><small>채광</small><strong>${lights[a.light]}</strong></div><div class="metric"><small>온도</small><strong>${a.temperatureC==null?'입력 안 함':a.temperatureC+'°C'}</strong></div></div>${a.summary?`<p>${escape(a.summary)}</p>`:`<p>${['직접 햇빛이 많이 드는 공간이에요.','강한 직사광선보다 밝은 간접광이 드는 공간이에요.','직접 햇빛은 적고 부드러운 빛이 드는 공간이에요.','자연광이 적게 드는 공간이에요.'][a.light]}</p>`}${a.evidence?.length?`<div class="notice">${a.evidence.map(t=>`<div>· ${escape(t)}</div>`).join('')}</div>`:''}${button('나에게 딱 맞는 식구를 추천받고 싶어요','analysis-recommend','wide')}${button('저장하고 홈으로','analysis-home','secondary wide')}${button('수정할게요','analysis-edit','text wide')}${button('사진 다시 분석하기','analyze','text wide')}`}`;}
function questionnaire(){const [key,title,options]=questions[question];return `<span class="tiny">Care profile · ${question+1} / 4</span><div class="progress"><span style="width:${(question+1)*25}%"></span></div><h1>${title}</h1><p>정답은 없어요. 나의 일상에 맞게 골라주세요.</p><div class="stack">${options.map((o,i)=>`<button class="choice ${answers[key]===(key==='size'?sizePreferenceValues[i]:i)?'active':''}" data-action="answer:${key==='size'?sizePreferenceValues[i]:i}" aria-pressed="${answers[key]===(key==='size'?sizePreferenceValues[i]:i)}">${o}<span>${answers[key]===(key==='size'?sizePreferenceValues[i]:i)?'✓':''}</span></button>`).join('')}</div>${button(question===3?(state.signupDraft&&!member()?'가입하고 식구 만나기':'내 관리 성향 저장하기'):'다음 →','question-next','wide',answers[key]==null?'disabled':'')}${question?button('이전 질문','question-prev','text wide'):''}${button(member()?'수정 취소':'가입은 나중에 할게요','care-exit','text wide')}<small>나중에 마이페이지에서 언제든 수정할 수 있어요.</small>`;}
function recommendations(){const list=ranked();return `<span class="tiny">Grow fit / Curated for you</span><h1>${escape(activeSpace().name)}에서 함께할<br>식구를 찾았어요.</h1><p>공간 환경과 관리 성향을 함께 고려했어요.</p><div class="row"><span class="badge">${lights[activeSpace().analysis.light]} · ${questions[1][2][state.careProfile.frequency]}</span>${link('수정','/my-page','muted')}</div>${list.length?list.map(plantCard).join(''):empty('현재 조건에 맞는 추천 식물이 없어요','공간 조건을 수정하거나 전체 식물을 둘러보세요.','조건 수정','/space/result')}${link('전체 식물 탐색하기','/explore','btn secondary wide')}`;}
const filterDefinitions=[['types','종류',plantTypes.map(v=>[v,v])],['light','채광',lights.map((v,i)=>[i,v])],['difficulty','난이도',difficulties.map((v,i)=>[i,v])],['size','크기',sizeOrder.map(i=>[i,sizes[i]])],['features','특징',['건조에 강함','습도 선호','잎 감상'].map(v=>[v,v])]];
const filtersFor=scope=>scope==='viz'?state.visualizerFilters:state.exploreFilters;
function filtered(){return filterPlants(plants,state.exploreFilters);}
function filterPanel(scope){const f=filtersFor(scope),prefix=scope==='viz'?'viz-':'',id=scope==='viz'?'viz-search':'search';return `<div class="plant-filter-panel"><label for="${id}">식물 이름 검색</label><input id="${id}" type="search" placeholder="식물 이름을 검색해보세요" value="${escape(f.query)}"><details id="${scope}-filters" ${scope==='viz'?'open':''}><summary>종류 · 채광 · 난이도 · 크기 · 특징</summary>${filterDefinitions.map(([key,label,options])=>`<fieldset class="filter-group"><legend>${label}</legend><div class="filters">${options.map(([v,text])=>`<button class="chip ${f[key].includes(v)?'active':''}" aria-pressed="${f[key].includes(v)}" data-action="${prefix}filter:${key}:${v}">${text}</button>`).join('')}</div></fieldset>`).join('')}<small>크기는 사진 속 개체를 기준으로 보며, 성장에 따라 달라질 수 있어요.</small></details></div>`;}
function filterSummary(scope,count){const f=filtersFor(scope),prefix=scope==='viz'?'viz-':'';return `<div class="filters">${filterDefinitions.flatMap(([key,label,options])=>f[key].map(v=>`<button class="chip active" data-action="${prefix}filter:${key}:${escape(v)}">${escape(options.find(([value])=>value===v)?.[1]||v)} ×</button>`)).join('')}</div><div class="sectionhead"><p role="status">식물 ${count}개</p>${button('필터 초기화',prefix+'filters-clear','text')}</div>`;}
function explore(){return `<span class="tiny">MY seekgoo of destiny</span><h1>새로운 내 식구 찾기</h1>${filterPanel('explore')}<div id="explore-results">${exploreResults()}</div>`;}
function exploreResults(){const list=filtered();return `${filterSummary('explore',list.length)}<div class="cards compact">${list.length?list.map(plantCard).join(''):`<div class="empty"><h2>조건에 맞는 식물이 없어요</h2><p>검색어나 필터를 바꿔보세요.</p>${button('필터 초기화','filters-clear','secondary wide')}</div>`}</div>`;}
function visualizerPlantResults(){const list=plantGroup==='saved'?plants.filter(p=>state.savedPlantIds.includes(p.id)):plantGroup==='recommended'?ranked():filterPlants(plants,state.visualizerFilters);return `${plantGroup==='all'?filterSummary('viz',list.length):''}<div class="selector" tabindex="0" aria-label="좌우로 넘겨서 선택하기">${list.length?list.map(p=>`<button class="${viz.plantId===p.id?'active':''}" data-action="viz-plant:${p.id}" aria-pressed="${viz.plantId===p.id}"><img src="${p.image}" alt="">${p.name}<br><small>${sizes[p.specimenSize]}</small>${match(p)?`<br><small>${match(p).score}점</small>`:''}</button>`).join(''):`<div class="selector-empty"><p>조건에 맞는 식물이 없어요.</p>${plantGroup==='all'?button('필터 초기화','viz-filters-clear','secondary'):button('전체 식물 보기','plant-group:all','secondary')}</div>`}</div>`;}
function refreshVizResults(){document.querySelector('#visualizer-results').innerHTML=visualizerPlantResults();bindHorizontalScroll(document.querySelector('.selector'));}
function detail(p){const m=match(p),tipKeys=['watering','light','pests','difficulty'],preferred=member()?tipKeys[state.careProfile.concern]:null,tipOrder=[...new Set([preferred,...tipKeys].filter(Boolean))];return `<div class="detail-image"><img src="${p.image}" alt="${p.name}"></div><span class="tiny">${p.english}</span><div class="row"><h1>${p.name}</h1><button class="icon ${state.savedPlantIds.includes(p.id)?'active':''}" aria-label="식물 저장" aria-pressed="${state.savedPlantIds.includes(p.id)}" data-action="save:${p.id}">${state.savedPlantIds.includes(p.id)?'♥':'♡'}</button></div><p>${p.description}</p><div class="filters">${p.types.map(type=>`<span class="badge">${type}</span>`).join('')}</div><div class="metrics"><div class="metric"><small>관리 난이도</small><strong>${difficulties[p.difficulty]}</strong></div><div class="metric"><small>좋아하는 빛</small><strong>${p.light.map(i=>lights[i]).join(' · ')}</strong></div><div class="metric"><small>관리 관찰 빈도</small><strong>${['낮음','보통','높음'][p.frequency]}</strong></div><div class="metric"><small>사진 속 식물 크기</small><strong>${sizes[p.specimenSize]}</strong></div></div>${m?`<div class="cardbody card"><div class="row"><h3>내 공간 적합도</h3><span class="score">${m.score}점</span></div><small>입력 조건 기준 적합도</small>${m.reasons.map(r=>`<p class="reason">✓ ${r}</p>`).join('')}${m.cautions.map(r=>`<p class="warn">△ ${r}</p>`).join('')}</div>`:`<div class="notice">${!member()?'관리 성향 테스트가 완료되지 않아 매칭 점수가 표시되지 않아요. 공간에 놓아보기는 바로 이용할 수 있어요.':'공간 정보를 확인하면 매칭 점수를 볼 수 있어요.'}</div>`}${link('내 공간에 놓아보기 ↗','/visualizer/'+p.id,'btn wide')}${button(state.comparePlantIds.includes(p.id)?'비교에서 빼기':'비교하기',`compare:${p.id}`,'secondary wide')}<h2>함께 지내는 방법</h2>${tipOrder.map(k=>`<details ${k===preferred?'open':''}><summary>${{watering:'물주기',light:'햇빛과 위치',pests:'잎 상태 살피기',difficulty:'관리 팁'}[k]}${k===preferred?' · 나의 걱정':''}</summary><p>${p.concernTips[k]}</p></details>`).join('')}<h2>어디에 두면 좋을까요?</h2>${p.placementTips.map(t=>`<p>${t}</p>`).join('')}`;}
function compare(){return `<span class="tiny">Side by side</span><h1>우리 집의 식구,<br>나란히 살펴보세요.</h1><p>최대 3개까지 비교할 수 있어요.</p>${state.comparePlantIds.length?`<div class="compare">${state.comparePlantIds.map(id=>{const p=find(id),m=match(p);return `<article><img src="${p.image}" alt="${p.name}"><h3 style="margin-top:14px">${link(p.name,'/plants/'+id,'')}</h3>${button('비교에서 빼기','compare:'+id,'text')}<div class="cell"><small>입력 조건 적합도</small><br><strong class="score">${m?m.score+'점':'—'}</strong></div><div class="cell"><small>난이도</small><br>${difficulties[p.difficulty]}</div><div class="cell"><small>채광</small><br>${p.light.map(i=>lights[i]).join(' · ')}</div><div class="cell"><small>물주기</small><br>${p.watering}</div><div class="cell"><small>관리 빈도 / 크기</small><br>${['낮음','보통','높음'][p.frequency]} / ${p.sizes.map(i=>sizes[i]).join(' · ')}</div><div class="cell"><small>특징</small><br>${p.features.join(' · ')}</div><div class="cell"><small>나와의 관리 궁합</small><br>${m?[...m.reasons,...m.cautions].join(' / '):'공간과 관리 성향 입력 후 확인'}</div>${link('놓아보기','/visualizer/'+id,'btn')}</article>`;}).join('')}${state.comparePlantIds.length<3?`<article>${link('＋ 식물 추가','/explore','btn secondary')}</article>`:''}</div>`:empty('비교할 식물을 골라주세요','탐색이나 상세에서 비교 버튼을 눌러보세요.')}`;}
const pos=(i,cols,rows)=>`${(i%cols)/(cols-1)*100}% ${Math.floor(i/cols)/(rows-1)*100}%`;
function composition(v,interactive=false){const p=find(v.plantId)||plants[0],pot=pots.find(p=>p.id===v.potId)||pots[0],soil=pot.soil??[.285,.265,.29,.16,.18,.19][pot.atlas],lip=pot.lip??[.33,.30,.34,.20,.23,.25][pot.atlas],cut=p.sheet||p.id==='p10'?1:[.96,.96,.98,.98,.95,.94,.98,.98,.98,.98,1,1][p.atlas],overhang=p.overhang||p.id==='p06',plantClass=p.id==='p10'?'lucky-cutout':p.sheet?'plant-sheet-'+p.sheet:'',potClass=pot.sheet?'additional-pot':'',geometry=plantGeometry(p);return `<div class="composition ${overhang?'overhang':''}" ${interactive?'id="composition" tabindex="0" role="group" aria-label="식물 배치. 방향키로 이동할 수 있어요"':''} style="left:${v.transform.x*100}%;top:${v.transform.y*100}%;width:${44*geometry.scene*v.transform.scale}%;--plant-width:${geometry.width}%;--pot-top:${(1-.58*soil)/1.37*100}%;--front-lip:${lip*100}%;--plant-top:${geometry.top}%;--plant-cut:${(1-cut)*100}%;--plant-left:${geometry.left}%"><div class="pot-layer pot-back ${potClass}" style="background-position:${pos(pot.atlas,pot.sheet?4:3,2)}"></div><div class="plant-layer ${plantClass}" style="background-position:${p.id==='p10'?'center':pos(p.atlas,p.sheet?3:4,p.sheet?2:3)}"></div><div class="pot-layer pot-front ${potClass}" style="background-position:${pos(pot.atlas,pot.sheet?4:3,2)}"></div></div>`;}

function canvas(v,interactive=false){const space=state.spaces.find(s=>s.id===v.spaceId)||activeSpace();return `<div class="canvas" ${interactive?'id="canvas"':''}><img class="background" src="${photo(space)}" alt="${escape(space?.name)} 공간 사진">${composition(v,interactive)}</div>`;}
function visualizer(id){if(!ready()&&plantGroup==='recommended')plantGroup='all';if(!viz||viz.entry!==id||viz.spaceId!==state.activeSpaceId)viz={entry:id,spaceId:state.activeSpaceId,plantId:find(id)?.id||plants[0].id,potId:pots[0].id,transform:{x:.5,y:.65,scale:1}};const selected=find(viz.plantId),pot=pots.find(p=>p.id===viz.potId);return `<span class="tiny">Style fit / In your room</span><h1>우리 집에 놓아볼까요?</h1>${spacePicker()}<p>식물을 끌어 옮기고 크기를 조절해보세요.</p>${canvas(viz,true)}<p class="placement-note">식물별 상대 크기를 반영했어요. 사진 속 실제 치수와 원근감을 측정한 이미지는 아니므로 배치 참고용으로 봐주세요.</p><div class="sectionhead"><h2>${selected.name} <small>${sizes[selected.specimenSize]}</small></h2><small>${pot.name}</small></div><div class="filters">${button('식물 선택','tab:plants',tab==='plants'?'':'secondary')}${button('화분 선택','tab:pots',tab==='pots'?'':'secondary')}</div>${tab==='plants'?`<div class="filters">${[...(ready()?[['recommended','추천 식물']]:[]),['saved','저장한 식물'],['all','전체 식물']].map(([v,l])=>`<button class="chip ${plantGroup===v?'active':''}" data-action="plant-group:${v}">${l}</button>`).join('')}</div>${plantGroup==='all'?filterPanel('viz'):''}<div id="visualizer-results">${visualizerPlantResults()}</div>`:`<div class="row"><div><label for="pot-color">색상</label><select id="pot-color"><option value="">전체</option>${[...new Set(pots.map(p=>p.color))].map(v=>`<option ${potColor===v?'selected':''}>${v}</option>`).join('')}</select></div><div><label for="pot-material">재질</label><select id="pot-material"><option value="">전체</option>${[...new Set(pots.map(p=>p.material))].map(v=>`<option ${potMaterial===v?'selected':''}>${v}</option>`).join('')}</select></div></div><div class="selector" tabindex="0" aria-label="좌우로 넘겨서 선택하기">${pots.filter(p=>(!potColor||potColor===p.color)&&(!potMaterial||potMaterial===p.material)).map(p=>`<button class="${viz.potId===p.id?'active':''}" data-action="viz-pot:${p.id}"><div class="pot-thumb ${p.sheet?'additional-pot':''}" style="background-position:${pos(p.atlas,p.sheet?4:3,2)}"></div>${p.name}</button>`).join('')||'<p>조건에 맞는 화분이 없어요.</p>'}</div>`}<div class="controls"><div class="row"><label for="scale">크기 <output id="scale-label">${Math.round(viz.transform.scale*100)}%</output></label>${button('위치 초기화','viz-reset','text')}</div><div class="row">${button('−','scale-down','secondary','aria-label="크기 줄이기"')}<input id="scale" type="range" min="0.5" max="1.5" step="0.05" value="${viz.transform.scale}" aria-label="식물 크기">${button('＋','scale-up','secondary','aria-label="크기 늘리기"')}</div></div>${button('이 조합 저장하기','save-combo','wide')}`;}
function combinations(spaceId=null){return state.savedCombinations.filter(c=>(!spaceId||c.spaceId===spaceId)&&state.spaces.some(s=>s.id===c.spaceId)).map(c=>`<article class="combo">${canvas(c)}<span class="badge">${escape(state.spaces.find(s=>s.id===c.spaceId).name)}</span><div class="row" style="margin-top:12px"><strong>${find(c.plantId).name}</strong><small>${pots.find(p=>p.id===c.potId).name}</small></div>${c.placementNeedsReview?'<p class="warn">사진이 바뀌어 배치를 다시 확인해주세요.</p>':''}<div class="row">${button('배치 열기','open-combo:'+c.id,'text')}${button('삭제','delete-combo:'+c.id,'text')}</div></article>`).join('')||empty('아직 저장한 조합이 없어요','식물 상세에서 내 공간에 놓아보세요.');}
function saved(){return `<span class="tiny">Your shortlist</span><h1>마음에 담은 식구</h1><h2>저장한 식물 <small>${state.savedPlantIds.length}</small></h2><div class="cards compact">${state.savedPlantIds.map(id=>plantCard(find(id))).join('')||empty('아직 저장한 식물이 없어요','마음에 드는 식물의 하트를 눌러주세요.')}</div><h2>저장한 조합 <small>${state.savedCombinations.length}</small></h2>${combinations()}`;}
function mySpace(){const profile=member()?state.careProfile:null;return `<h1>마이페이지</h1><section class="profile-summary">${member()?`<p class="member-name">${escape(state.account.username)} 님, 반가워요.</p><div class="sectionhead"><h2>나의 관리 성향</h2>${button('수정','care-edit','text')}</div><p>${questions[0][2][profile.experience]} · ${questions[1][2][profile.frequency]}</p><div class="filters"><span class="badge">${questions[2][2][profile.concern]}이 걱정돼요</span><span class="badge">${profile.size===3?'크기는 상관없어요':sizes[profile.size===4?3:profile.size]+'을 좋아해요'}</span></div>${button('로그아웃','logout','text')}`:`<h2>나의 운명의 식구를 만나보세요</h2><p>가입할 때 알려주신 관리 성향으로 나에게 맞는 식물을 찾아드려요.</p>${link('로그인하고 운명의 식구 추천받기','/auth','btn wide')}`}</section><div class="sectionhead"><h2>나의 공간 <small>${state.spaces.length} / 4</small></h2>${state.spaces.length<4?button('＋ 등록','new-space','text'):''}</div>${state.spaces.length?state.spaces.map(space=>`<article class="space-card"><img class="room" src="${photo(space)}" alt="${escape(space.name)}"><div class="sectionhead"><h3>${escape(space.name)}</h3><span class="badge">${space.analysisConfirmed?lights[space.analysis.light]:'정보 입력'}</span></div><small>${escape(space.type)} · 저장 조합 ${state.savedCombinations.filter(c=>c.spaceId===space.id).length}</small><div class="space-actions">${button('공간 정보','space-info:'+space.id,'secondary')}${button('사진 교체','space-photo:'+space.id,'secondary')}${button('이름 수정','rename-space:'+space.id,'text')}${button('삭제','delete-space:'+space.id,'text')}</div>${button('이 공간에 놓아보기','space-place:'+space.id,'wide')}</article>`).join(''):empty('초록을 들일 자리를 알려주세요','최대 4개의 공간을 등록할 수 있어요.','내 공간 등록하기','/space/new')}<h2>저장한 조합</h2>${combinations()}`;}
function startNewSpace(){if(state.spaces.length>=4){toast('공간은 최대 4개까지 등록할 수 있어요.');return;}const next=structuredClone(state);next.pendingSpace={id:newId(),type:'거실',name:''};if(commit(next)){spaceType='거실';pendingName='';go('/space/new');}}
function selectSpace(id){if(!state.spaces.some(s=>s.id===id))return false;const next=structuredClone(state);next.activeSpaceId=id;next.pendingSpace=null;if(commit(next)){viz=null;editAnalysis=false;return true;}return false;}
function beginCare(destination='/'){careDestination=destination;answers={...((member()?state.careProfile:state.careDraft)||{})};question=member()?0:Math.max(0,questions.findIndex(([k])=>answers[k]==null));go('/profile/care');}
function requestRecommendation(){if(!member()){go('/auth');return;}if(!activeSpace()){startNewSpace();return;}if(!activeSpace().analysisConfirmed){go('/space/result');return;}go('/recommendations');}
function analysisLoading(){return analysisError?`<div class="loading"><span class="tiny">Your space</span><h1>사진을 확인하지<br>못했어요.</h1><p role="alert">${escape(analysisError)}</p>${button('다시 분석하기','analyze','wide')}${button('공간 정보 직접 입력하기','analysis-manual','secondary wide')}${link('사진 바꾸기','/space/photo','btn text wide')}</div>`:`<div class="loading"><span class="tiny">Finding the light</span><h1>공간의 빛을<br>살펴보고 있어요.</h1><p>창문과 햇빛, 그림자를 확인하고 있어요.</p><div class="progress indeterminate"><span></span></div>${button('홈으로 돌아가기','exit','text wide')}</div>`;}

function intro(){const slides=[['01 / YOUR SPACE','식구가 머무를<br>자리를 알려주세요.','거실 창가부터 작은 베란다까지.<br>우리 집의 초록 자리를 담아보세요.'],['02 / YOUR MATCH','나의 일상에 맞는<br>식구를 만나세요.','공간의 빛과 나의 관리 성향으로<br>함께 지내기 좋은 식물을 찾아드려요.'],['03 / YOUR HOME','우리 집에 먼저<br>놓아보세요.','식물과 화분을 바꿔보며<br>마음에 드는 풍경을 완성해보세요.']];return `<section class="welcome"><div class="welcome-top"><span class="tiny">Meet your seekgoo</span>${button('건너뛰기','intro-finish','text')}</div><div class="intro-slides" tabindex="0" role="region" aria-label="식구 소개. 좌우로 밀어서 넘겨주세요">${slides.map(([step,title,copy],i)=>`<article class="intro-slide" aria-label="${i+1} / 3"><div class="intro-art art-${i}">${i===0?'<img draggable="false" src="assets/demo/room.png" alt="식물을 놓을 밝은 실내 공간"><span class="floating-label">나의 공간 ＋</span>':i===1?'<img draggable="false" src="assets/plants/ref-4.png" alt="햇빛을 받은 몬스테라"><span class="floating-label">나의 일상에 맞는 초록</span>':`<img draggable="false" src="assets/demo/room.png" alt="식물이 놓인 우리 집 미리보기">${composition({plantId:'p05',potId:'pot0',transform:{x:.54,y:.7,scale:1.1}})}<span class="floating-label">Plant + Pot + My room</span>`}</div><span class="tiny intro-step">${step}</span><h1>${title}</h1><p>${copy}</p>${i===2?button('식구 시작하기 →','intro-finish','wide'):''}</article>`).join('')}</div><div class="intro-bottom"><div class="intro-dots" aria-label="소개 페이지">${slides.map((_,i)=>`<button data-action="intro-page:${i}" class="${i===introIndex?'active':''}" aria-label="${i+1}번째 소개" aria-current="${i===introIndex?'step':'false'}"></button>`).join('')}</div><small>좌우로 넘겨보세요 ↔</small></div></section>`;}

function auth(){return `<section class="auth-page"><span class="tiny">Meet your destined green</span><h1>나의 운명의 식구,<br>여기서 만나요.</h1><div class="auth-art"><img src="assets/plants/ref-0.png" alt="동그란 잎의 필레아"></div><p>나를 닮은 일상,<br>함께할 식구를 찾아드릴게요.</p>${link('로그인하고 운명의 식구 추천받기',state.account?'/login':'/signup','btn wide')}${button('먼저 둘러보기','browse','secondary wide')}${state.signupDraft&&!state.account?button('작성하던 가입 이어하기','resume-signup','text wide'):''}${!state.account?link('이미 아이디가 있어요','/login','btn text wide'):''}</section>`;}
function signup(){if(state.account)return login();return `<span class="tiny">Welcome to seekgoo</span><h1>식구가 되어주세요.</h1><p>아이디를 만들고 나의 관리 성향을 알려주세요.</p><form id="signup-form"><label for="username">아이디</label><input id="username" name="username" autocomplete="username" minlength="2" maxlength="20" required pattern="[A-Za-z0-9가-힣_]{2,20}" placeholder="식구에서 사용할 이름" value="${escape(state.signupDraft?.username||'')}"><small>한글·영문·숫자·밑줄, 2~20자</small><div class="agreements"><label><input type="checkbox" id="agree-service" required ${state.signupDraft?'checked':''}> [필수] 서비스 이용 동의</label><details><summary>내용 보기</summary><p>식물 정보와 배치 이미지는 식물을 선택하기 위한 참고 정보입니다. 내 공간과 식물 상태를 확인하며 이용해주세요.</p></details><label><input type="checkbox" id="agree-storage" required ${state.signupDraft?'checked':''}> [필수] 정보 저장 동의</label><details><summary>내용 보기</summary><p>아이디, 관리 성향, 공간 사진과 저장한 식구는 이 브라우저에 저장됩니다. 브라우저 데이터를 삭제하면 함께 삭제됩니다. 사진 분석을 요청할 때는 선택한 사진이 분석 서비스로 전달됩니다.</p></details></div><button type="submit" class="btn wide">동의하고 나의 관리 성향 알아보기</button></form>${button('가입은 나중에 할게요','browse','text wide')}`;}
function login(){return `<span class="tiny">Welcome back</span><h1>다시 만나 반가워요.</h1><p>이전에 만든 아이디로 들어오세요.</p><form id="login-form"><label for="login-id">아이디</label><input id="login-id" autocomplete="username" required maxlength="20" placeholder="나의 아이디"><button class="btn wide" type="submit">로그인</button></form>${!state.account?link('아이디 만들기','/signup','btn secondary wide'):''}${button('먼저 둘러보기','browse','text wide')}`;}
function finishIntro(){const next=structuredClone(state);next.introSeen=true;if(commit(next))go('/auth');}
function startSignup(){const input=document.querySelector('#username');if(!input.checkValidity()){input.reportValidity();return;}if(!document.querySelector('#agree-service').checked||!document.querySelector('#agree-storage').checked){toast('필수 항목에 동의해주세요.');return;}const next=structuredClone(state);next.signupDraft={username:input.value.trim(),agreedAt:new Date().toISOString()};next.careDraft={};if(commit(next)){answers={};question=0;careDestination='/';go('/profile/care');}}
function signIn(){const id=document.querySelector('#login-id').value.trim();if(!state.account||state.account.username!==id){toast('이 브라우저에 저장된 아이디를 확인해주세요.');return;}const next=structuredClone(state);next.signedIn=true;if(commit(next))go('/');}

function render(){const route=location.hash.slice(1)||'/';if(route==='/profile/care'&&!member()&&!state.signupDraft){go('/auth');return;}if(lastRoute==='/space/analyzing'&&route!=='/space/analyzing'){analysisController?.abort();analysisController=null;analysisJob=null;analysisError='';}if(route==='/my-space'){go('/my-page');return;}if(route==='/space/new'&&state.spaces.length>=4){toast('공간은 최대 4개까지 등록할 수 있어요.');go('/my-page');return;}if(route==='/space/new'&&!state.pendingSpace){startNewSpace();return;}if(['/space/result','/space/analyzing'].includes(route)&&!photo()){go('/space/photo');return;}if(route==='/recommendations'&&!ready()){requestRecommendation();return;}if(route==='/profile/care'&&lastRoute!==route&&Object.keys(answers).length===0){answers={...((member()?state.careProfile:state.careDraft)||{})};question=Math.max(0,questions.findIndex(([k])=>answers[k]==null));}lastRoute=route;let title='',body='',onboarding=/^\/space|^\/profile|^\/intro|^\/auth|^\/signup|^\/login/.test(route);
if(route==='/intro'){title='식구 소개';body=intro();}else if(route==='/auth'){title='식구 시작하기';body=auth();}else if(route==='/signup'){title='회원가입';body=signup();}else if(route==='/login'){title='로그인';body=login();}else if(route==='/')body=home();else if(route==='/space/new'){title='공간 등록';body=setup();}else if(route==='/space/photo'){title='공간 사진';body=upload();}else if(route==='/space/analyzing'){title='공간 분석';body=analysisLoading();}else if(route==='/space/result'){title='공간 정보';body=analysis();}else if(route==='/profile/care'){title='나의 관리 성향';body=questionnaire();}else if(route==='/recommendations'){title='맞춤 추천';body=recommendations();}else if(route==='/explore'){title='식물 탐색';body=explore();}else if(route.startsWith('/plants/')){const p=find(route.split('/')[2]);title='식물 이야기';body=p?detail(p):empty('식물을 찾을 수 없어요','다른 식물을 둘러보세요.');}else if(route==='/compare'){title='식물 비교';body=compare();}else if(route.startsWith('/visualizer')){title='내 공간에 놓아보기';body=photo()?visualizer(route.split('/')[2]):empty('공간 사진이 필요해요','나의 공간 사진 위에 식물을 놓아볼 수 있어요.','내 공간 등록하기','/space/new');}else if(route==='/saved'){title='저장';body=saved();}else if(route==='/my-page'){title='마이페이지';body=mySpace();}else if(route==='/success'){title='조합 저장';body=`<div class="success"><div class="success-mark">✓</div><h1>조합을 저장했어요.</h1><p>마음에 드는 풍경을 언제든 다시 꺼내보세요.</p>${viz?canvas(viz):''}${link('저장한 조합 보기','/saved','btn wide')}${link('다른 조합 만들어보기','/visualizer/'+(viz?.plantId||plants[0].id),'btn secondary wide')}${link('식물 상세로 돌아가기','/plants/'+(viz?.plantId||plants[0].id),'btn secondary small-return wide')}${link('홈으로 돌아가기','/','btn secondary small-return wide')}</div>`;}else{go('/');return;}
app.innerHTML=(splashVisible?'<div class="splash" role="status" aria-label="식구를 준비하고 있어요"><img src="assets/brand/logo-transparent.png" alt="seekgoo"><p>Find your plant. Meet your 식구.</p></div>':'')+(route==='/intro'?'':header(route,title,onboarding))+`<main>${body}</main>`+(!onboarding?nav(route):'')+(!onboarding&&state.comparePlantIds.length&&!['/compare','/success'].includes(route)&&!route.startsWith('/visualizer')?`<a class="tray row" href="#/compare"><span>비교 ${state.comparePlantIds.length}/3</span><span>나란히 보기 →</span></a>`:'');if(route.startsWith('/visualizer')&&photo()){bindDrag();bindHorizontalScroll(document.querySelector('.selector'));}if(route==='/intro')bindIntro();if(route==='/space/analyzing'&&!analysisJob&&!analysisError)void performAnalysis();}
async function performAnalysis(){const space=activeSpace();if(!space||analysisJob)return;const controller=new AbortController();analysisController=controller;const job={id:space.id,revision:space.photoRevision};analysisJob=job;
 try{let src=photo(space);if(!src.startsWith('data:')){const img=new Image();img.src=src;await img.decode();const c=document.createElement('canvas');c.width=768;c.height=Math.round(img.naturalHeight/img.naturalWidth*768);c.getContext('2d').drawImage(img,0,0,c.width,c.height);src=c.toDataURL('image/jpeg',.8);}const result=await analyzeImage(src,space.type,controller.signal);if(controller.signal.aborted||analysisJob!==job)return;const next=structuredClone(state),target=next.spaces.find(s=>s.id===job.id);if(!target||target.photoRevision!==job.revision)return;target.analysis={...result,...(target.analysis?.temperatureC!=null?{temperatureC:target.analysis.temperatureC}:{})};target.analysisConfirmed=false;target.analysisCompleted=true;if(commit(next)){editAnalysis=false;go('/space/result');}else{analysisError='결과를 저장하지 못했어요. 저장 공간을 확인해주세요.';render();}}
 catch(error){if(controller.signal.aborted)return;analysisError=error.message||'사진을 분석하지 못했어요.';render();}
}
async function savePhoto(src,room=null,context=null){const next=structuredClone(state),meta=context?.meta||next.pendingSpace;const old=context?next.spaces.find(s=>s.id===context.id):meta?null:activeSpace();if(context?.id&&!old){toast('공간이 변경되었어요. 다시 선택해주세요.');return;}if(!old&&next.spaces.length>=4){toast('공간은 최대 4개까지 등록할 수 있어요.');return;}const space={...(old||{}),id:old?.id||meta?.id||newId(),name:old?.name||meta?.name||meta?.type||'거실',type:old?.type||meta?.type||'거실',imageSource:room?'capture':'upload',imageDataUrl:src,captureAssetId:room?.id||null,photoRevision:(old?.photoRevision||0)+1,analysis:{...(old?.analysis?.temperatureC!=null?{temperatureC:old.analysis.temperatureC}:{})},analysisCompleted:false,analysisConfirmed:false};delete space.demoAssetId;next.spaces=old?next.spaces.map(s=>s.id===old.id?space:s):[...next.spaces,space];next.activeSpaceId=space.id;next.pendingSpace=null;next.savedCombinations=next.savedCombinations.map(c=>c.spaceId===space.id?{...c,transform:{x:.5,y:.65,scale:1},placementNeedsReview:true}:c);try{write(next);state=next;viz=null;pendingName='';editAnalysis=false;render();toast('공간 사진을 저장했어요.');return true;}catch{toast('사진을 저장하지 못했어요. 더 작은 사진을 선택해주세요.');return false;}}
function photoContext(){return state.pendingSpace?{meta:structuredClone(state.pendingSpace)}:{id:activeSpace()?.id};}
async function capturePhoto(){if(photoBusy)return;const context=photoContext(),space=uploadSpace(),type=context.meta?.type||space?.type||'거실',room=chooseRoom(type,space?.captureAssetId);photoBusy=true;render();try{const data=await roomImageData(room);await savePhoto(data,room,context);}catch{toast('사진을 준비하지 못했어요. 다시 촬영해주세요.');}finally{photoBusy=false;render();}}
async function uploadFile(file){if(!file||photoBusy)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)){toast('JPG, PNG, WebP 사진을 선택해주세요.');return;}const context=photoContext();photoBusy=true;render();try{if(file.size>30*1024*1024)throw Error();const bitmap=await createImageBitmap(file),ratio=Math.min(1,1000/Math.max(bitmap.width,bitmap.height)),c=document.createElement('canvas');c.width=Math.max(1,Math.round(bitmap.width*ratio));c.height=Math.max(1,Math.round(bitmap.height*ratio));c.getContext('2d').drawImage(bitmap,0,0,c.width,c.height);bitmap.close();await savePhoto(c.toDataURL('image/jpeg',.72),null,context);}catch{toast('사진을 열지 못했어요. 다른 사진으로 다시 시도해주세요.');}finally{photoBusy=false;render();}}


// Keep the horizontal browsing position and keyboard focus when changing an item.
function renderSelection(action){
 const left=document.querySelector('.selector')?.scrollLeft||0;
 const filterOpen=document.querySelector('#viz-filters')?.open;
 const top=window.scrollY;
 render();
 const selector=document.querySelector('.selector');
 if(selector)selector.scrollLeft=left;
 if(document.querySelector('#viz-filters')&&filterOpen!==undefined)document.querySelector('#viz-filters').open=filterOpen;
 document.querySelector(`[data-action="${action}"]`)?.focus({preventScroll:true});
 window.scrollTo({top,left:window.scrollX,behavior:'instant'});
}
function updateTransform(){const el=document.querySelector('#composition');if(el){el.style.left=viz.transform.x*100+'%';el.style.top=viz.transform.y*100+'%';el.style.width=44*find(viz.plantId).sceneScale*viz.transform.scale+'%';}const range=document.querySelector('#scale'),label=document.querySelector('#scale-label');if(range)range.value=viz.transform.scale;if(label)label.textContent=Math.round(viz.transform.scale*100)+'%';}
function bindDrag(){const el=document.querySelector('#composition'),parent=document.querySelector('#canvas');let start=null;// Pointer coordinates and image-normalized placement are deliberately separate.
el.onpointerdown=e=>{e.preventDefault();el.setPointerCapture(e.pointerId);start={clientX:e.clientX,clientY:e.clientY,x:viz.transform.x,y:viz.transform.y};};el.onpointermove=e=>{if(!start)return;const b=parent.getBoundingClientRect();viz.transform.x=Math.max(.05,Math.min(.95,start.x+(e.clientX-start.clientX)/b.width));viz.transform.y=Math.max(.05,Math.min(.95,start.y+(e.clientY-start.clientY)/b.height));updateTransform();};el.onpointerup=el.onpointercancel=()=>start=null;el.onkeydown=e=>{const d={ArrowLeft:[-.02,0],ArrowRight:[.02,0],ArrowUp:[0,-.02],ArrowDown:[0,.02]}[e.key];if(d){e.preventDefault();viz.transform.x=Math.max(.05,Math.min(.95,viz.transform.x+d[0]));viz.transform.y=Math.max(.05,Math.min(.95,viz.transform.y+d[1]));updateTransform();}};}
app.addEventListener('input',e=>{if(e.target.id==='space-name'){pendingName=e.target.value;if(state.pendingSpace)state.pendingSpace.name=pendingName;}if(e.target.id==='search'){const next=structuredClone(state);next.exploreFilters.query=e.target.value;if(commit(next))document.querySelector('#explore-results').innerHTML=exploreResults();}if(e.target.id==='viz-search'){const next=structuredClone(state);next.visualizerFilters.query=e.target.value;if(commit(next))refreshVizResults();}if(e.target.id==='scale'){viz.transform.scale=Number(e.target.value);updateTransform();}});
app.addEventListener('change',e=>{if(e.target.id==='photo-file')void uploadFile(e.target.files[0]);if(e.target.id==='pot-color'){potColor=e.target.value;render();}if(e.target.id==='pot-material'){potMaterial=e.target.value;render();}});
app.addEventListener('click',e=>{const target=e.target.closest('[data-action]');if(!target)return;const [action,arg,arg2]=target.dataset.action.split(':');let next;
switch(action){
case'intro-page':introIndex=Number(arg);{const slider=document.querySelector('.intro-slides');slider?.scrollTo({left:introIndex*slider.clientWidth,behavior:window.matchMedia?.('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});}break;case'intro-finish':finishIntro();break;case'browse':next=structuredClone(state);next.introSeen=true;next.signedIn=false;if(commit(next))go('/');break;case'resume-signup':if(state.signupDraft)beginCare('/');break;case'logout':next=structuredClone(state);next.signedIn=false;if(commit(next))go('/');break;
case'back':if(location.hash==='#/profile/care'){if(question>0){question--;render();}else exitCare();}else if(history.length>1)history.back();else go('/');break;
case'exit':go('/');break;case'new-space':startNewSpace();break;case'select-space':if(selectSpace(arg))render();break;
case'type':spaceType=arg;next=structuredClone(state);next.pendingSpace={...(next.pendingSpace||{id:newId(),name:''}),type:arg};if(commit(next))render();break;
case'setup-next':{if(state.spaces.length>=4){toast('공간은 최대 4개까지 등록할 수 있어요.');return;}next=structuredClone(state);next.pendingSpace={id:next.pendingSpace?.id||newId(),type:spaceType,name:pendingName.trim()||spaceType};if(commit(next))go('/space/photo');break;}
case'choose-photo':document.querySelector('#photo-file').click();break;case'camera':void capturePhoto();break;
case'space-info':if(selectSpace(arg))go('/space/result');break;case'space-photo':if(selectSpace(arg))go('/space/photo');break;case'space-place':if(selectSpace(arg))go('/visualizer/'+plants[0].id);break;
case'rename-space':{const old=state.spaces.find(s=>s.id===arg),name=prompt('공간 이름을 입력해주세요.',old.name);if(name===null)break;if(!name.trim()||name.trim().length>30){toast('공간 이름을 1~30자로 입력해주세요.');break;}next=structuredClone(state);next.spaces.find(s=>s.id===arg).name=name.trim();if(commit(next))render();break;}
case'delete-space':{const old=state.spaces.find(s=>s.id===arg);if(!confirm(`${old.name} 공간과 이 공간의 저장 조합을 삭제할까요?`))break;next=structuredClone(state);next.spaces=next.spaces.filter(s=>s.id!==arg);next.savedCombinations=next.savedCombinations.filter(c=>c.spaceId!==arg);if(next.activeSpaceId===arg)next.activeSpaceId=next.spaces[0]?.id||null;if(commit(next)){viz=null;render();toast('공간을 삭제했어요.');}break;}
case'analyze':if(!photo(uploadSpace())){toast('공간 사진을 먼저 선택해주세요.');return;}analysisController?.abort();analysisJob=null;analysisError='';go('/space/analyzing');break;
case'analysis-manual':editAnalysis=true;go('/space/result');break;case'analysis-edit':editAnalysis=true;render();break;
case'analysis-save':{const light=document.querySelector('#light'),temp=document.querySelector('#temperature');if(light.value===''){toast('채광을 선택해주세요.');light.focus();return;}if(!temp.checkValidity()){temp.reportValidity();return;}next=structuredClone(state);const space=next.spaces.find(s=>s.id===next.activeSpaceId);space.analysis={light:Number(light.value),source:'manual',...(temp.value!==''?{temperatureC:Number(temp.value)}:{})};space.analysisConfirmed=false;if(commit(next)){editAnalysis=false;render();toast('공간 정보를 저장했어요.');}break;}
case'analysis-home':case'analysis-recommend':{next=structuredClone(state);const space=next.spaces.find(s=>s.id===next.activeSpaceId);if(!Number.isInteger(space?.analysis?.light)){toast('채광 정보를 먼저 입력해주세요.');return;}space.analysisConfirmed=true;if(commit(next)){if(action==='analysis-home')go('/');else requestRecommendation();}break;}
case'recommend':requestRecommendation();break;case'care-edit':if(member())beginCare('/my-page');else go('/auth');break;case'care-exit':exitCare();break;
case'answer':answers[questions[question][0]]=Number(arg);next=structuredClone(state);next.careDraft={...answers};if(commit(next))render();break;case'question-prev':question--;render();break;
case'question-next':if(answers[questions[question][0]]==null)return;if(question<3){question++;render();}else if(questions.every(([k])=>answers[k]!=null)){next=structuredClone(state);next.careProfile={...answers};next.careDraft={};next.onboardingSeen=true;if(next.signupDraft&&!member()){next.account={...next.signupDraft,createdAt:new Date().toISOString()};next.signedIn=true;next.signupDraft=null;}if(commit(next)){question=0;answers={};toast('관리 성향을 저장했어요.');if(careDestination==='/recommendations')requestRecommendation();else go(careDestination);}}break;
case'save':next=structuredClone(state);next.savedPlantIds=next.savedPlantIds.includes(arg)?next.savedPlantIds.filter(x=>x!==arg):[...next.savedPlantIds,arg];if(commit(next)){render();toast(state.savedPlantIds.includes(arg)?'식물을 저장했어요.':'저장을 취소했어요.');}break;
case'compare':next=structuredClone(state);if(next.comparePlantIds.includes(arg))next.comparePlantIds=next.comparePlantIds.filter(x=>x!==arg);else{if(next.comparePlantIds.length===3){toast('최대 3개까지 비교할 수 있어요.');return;}next.comparePlantIds.push(arg);}if(commit(next)){render();toast('비교 목록을 변경했어요.');}break;
case'filter':next=structuredClone(state);{const val=['features','types'].includes(arg)?arg2:Number(arg2),list=next.exploreFilters[arg];next.exploreFilters[arg]=list.includes(val)?list.filter(x=>x!==val):[...list,val];}if(commit(next)){const open=document.querySelector('details')?.open;render();if(document.querySelector('details'))document.querySelector('details').open=open;}break;
case'viz-filter':{const open=document.querySelector('#viz-filters')?.open;next=structuredClone(state);const val=['features','types'].includes(arg)?arg2:Number(arg2),list=next.visualizerFilters[arg];next.visualizerFilters[arg]=list.includes(val)?list.filter(v=>v!==val):[...list,val];if(commit(next)){render();document.querySelector('#viz-filters').open=open;document.querySelector(`[data-action="viz-filter:${arg}:${arg2}"]`)?.focus({preventScroll:true});}break;}
case'viz-filters-clear':next=structuredClone(state);next.visualizerFilters=fresh().visualizerFilters;if(commit(next))render();break;
case'filters-clear':next=structuredClone(state);next.exploreFilters=fresh().exploreFilters;if(commit(next))render();break;
case'tab':tab=arg;render();break;case'plant-group':plantGroup=arg;render();break;case'viz-plant':viz.plantId=arg;renderSelection('viz-plant:'+arg);break;case'viz-pot':viz.potId=arg;renderSelection('viz-pot:'+arg);break;case'viz-reset':viz.transform={x:.5,y:.65,scale:1};updateTransform();break;
case'scale-down':case'scale-up':viz.transform.scale=Math.min(1.5,Math.max(.5,viz.transform.scale+(action==='scale-up'?.05:-.05)));updateTransform();break;
case'save-combo':next=structuredClone(state);{const c={id:viz.id||newId(),spaceId:viz.spaceId,plantId:viz.plantId,potId:viz.potId,transform:{...viz.transform},createdAt:new Date().toISOString(),placementNeedsReview:false};next.savedCombinations=next.savedCombinations.filter(x=>x.id!==c.id);next.savedCombinations.push(c);}if(commit(next)){viz.id=next.savedCombinations.at(-1).id;toast('조합을 저장했어요.');go('/success');}break;
case'open-combo':{const c=state.savedCombinations.find(c=>c.id===arg);if(selectSpace(c.spaceId)){viz={...structuredClone(c),entry:c.plantId};go('/visualizer/'+c.plantId);}break;}
case'delete-combo':next=structuredClone(state);next.savedCombinations=next.savedCombinations.filter(c=>c.id!==arg);if(commit(next)){render();toast('조합을 삭제했어요.');}break;
}});
function exitCare(){const next=structuredClone(state);next.onboardingSeen=true;next.careDraft=member()?{}:{...answers};if(commit(next)){answers={};question=0;go(careDestination==='/my-page'?'/my-page':'/');}}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0);});
location.hash=state.introSeen?'/':'/intro';render();
setTimeout(()=>{splashVisible=false;render();},1900);


app.addEventListener('submit',e=>{if(e.target.id==='signup-form'){e.preventDefault();startSignup();}if(e.target.id==='login-form'){e.preventDefault();signIn();}});

// Native touch/trackpad scrolling plus mouse grab-to-scroll; a drag never selects a card.
function bindHorizontalScroll(el,snap=false){if(!el)return;let start=null,dragged=false,blockClickUntil=0;
 el.addEventListener('dragstart',e=>e.preventDefault());
 el.addEventListener('pointerdown',e=>{if(e.pointerType!=='mouse'||e.button!==0)return;start={x:e.clientX,left:el.scrollLeft,id:e.pointerId};dragged=false;});
 el.addEventListener('pointermove',e=>{if(!start)return;const dx=e.clientX-start.x;if(!dragged&&Math.abs(dx)>6){dragged=true;el.setPointerCapture(e.pointerId);el.classList.add('dragging');}if(dragged){e.preventDefault();el.scrollLeft=start.left-dx;}});
 const end=e=>{if(!start)return;const wasDragged=dragged;start=null;el.classList.remove('dragging');if(el.hasPointerCapture?.(e.pointerId))el.releasePointerCapture(e.pointerId);if(wasDragged){blockClickUntil=Date.now()+350;if(snap)el.scrollTo({left:Math.round(el.scrollLeft/el.clientWidth)*el.clientWidth,behavior:'smooth'});}};
 el.addEventListener('pointerup',end);el.addEventListener('pointercancel',end);el.addEventListener('pointerleave',e=>{if(!dragged)start=null;});
 el.addEventListener('click',e=>{if(Date.now()<blockClickUntil){e.preventDefault();e.stopPropagation();}},true);
}
function bindIntro(){const el=document.querySelector('.intro-slides');if(!el)return;el.scrollLeft=introIndex*el.clientWidth;bindHorizontalScroll(el,true);
 el.addEventListener('scroll',()=>{introIndex=Math.max(0,Math.min(2,Math.round(el.scrollLeft/el.clientWidth)));document.querySelectorAll('.intro-dots button').forEach((b,i)=>{b.classList.toggle('active',i===introIndex);b.setAttribute('aria-current',i===introIndex?'step':'false');});},{passive:true});
 el.addEventListener('keydown',e=>{if(e.target!==el||!['ArrowLeft','ArrowRight'].includes(e.key))return;e.preventDefault();introIndex=Math.max(0,Math.min(2,introIndex+(e.key==='ArrowRight'?1:-1)));el.scrollTo({left:introIndex*el.clientWidth,behavior:'smooth'});});
}
