const fs=require('fs'),vm=require('vm'),assert=require('node:assert/strict'),path=require('path');
const root=path.join(__dirname,'..');let code=['data','recommendation','storage','rooms','analysis','app'].map(f=>fs.readFileSync(path.join(root,'js',f+'.js'),'utf8')).join('\n').replace(/^import .*?;\n/gm,'').replace(/\bexport /g,'');
let values={},handlers={},hash='';const elements={};const elem=id=>elements[id]||(elements[id]={innerHTML:'',textContent:'',style:{},value:'',scrollLeft:0,clientWidth:382,listeners:{},classList:{add(){},remove(){},toggle(){}},setAttribute(){},scrollTo(o){this.scrollLeft=o.left;this.listeners.scroll?.({});},addEventListener(t,f){this.listeners[t]=f;if(id==='#app')handlers[t]=f;},setPointerCapture(){},focus(){},checkValidity(){return true;},getBoundingClientRect(){return {width:382,height:573}}});
const ctx={console,structuredClone,crypto:require('crypto').webcrypto,AbortController,location:{protocol:'file:',get hash(){return hash},set hash(v){hash=v.startsWith('#')?v:'#'+v}},history:{length:1},confirm:()=>true,prompt:()=>null,setTimeout(){},clearTimeout(){},window:{addEventListener(){},scrollTo(){}},document:{querySelector:elem,querySelectorAll:()=>[]},localStorage:{getItem:k=>values[k]||null,setItem:(k,v)=>values[k]=v,removeItem:k=>delete values[k]}};
vm.createContext(ctx);vm.runInContext(code,ctx);const run=s=>vm.runInContext(s,ctx);const click=action=>handlers.click({target:{closest:()=>({dataset:{action}})}});
assert.equal(hash,'#/intro');assert.match(elem('#app').innerHTML,/식구가 머무를/);
run('splashVisible=false');assert.ok(!elem('#app').innerHTML.includes('intro-next'));click('intro-page:1');assert.equal(run('introIndex'),1);click('intro-page:2');assert.equal(run('introIndex'),2);elem('.intro-slides').scrollLeft=0;elem('.intro-slides').listeners.scroll({});assert.equal(run('introIndex'),0);click('intro-finish');run('render()');assert.equal(hash,'#/auth');assert.ok(!elem('#app').innerHTML.includes('>나가기</button>'));assert.equal(run('state.introSeen'),true);click('browse');run('render()');assert.equal(hash,'#/');assert.equal(run('member()'),false);
click('new-space');run('render()');click('type:베란다');elem('#space-name').value='베란다 창가';handlers.input({target:{id:'space-name',value:'베란다 창가'}});click('setup-next');run('render()');
(async()=>{await run("savePhoto('data:image/jpeg;base64,/9j/','')");assert.equal(run('state.spaces.length'),1);assert.equal(run('activeSpace().name'),'베란다 창가');hash='#/space/result';run('render()');assert.ok(!elem('#app').innerHTML.includes('>나가기</button>'));assert.ok(!elem('#app').innerHTML.includes('이 공간에 놓아보기'));elem('#light').value='2';elem('#temperature').value='';click('analysis-save');click('analysis-home');run('render()');assert.equal(hash,'#/');assert.equal(run('state.careProfile'),null);assert.ok(!elem('#app').innerHTML.includes('저장 식물'));
// Guests can place and save, with no personalized score or test gate.
hash='#/visualizer/p03';run('render()');assert.match(elem('#app').innerHTML,/이 조합 저장하기/);assert.ok(!elem('#app').innerHTML.includes('점</small>'));elem('.selector').scrollLeft=840;click('viz-pot:pot13');assert.equal(run('viz.potId'),'pot13');assert.equal(elem('.selector').scrollLeft,840);click('viz-plant:p42');assert.equal(run('viz.plantId'),'p42');assert.equal(elem('.selector').scrollLeft,840);
// Drag the actual list and suppress the release click, while ordinary clicks remain available.
const rail=elem('.selector');let prevented=false,stopped=false;
rail.listeners.pointerdown({pointerType:'mouse',button:0,clientX:200,pointerId:1});rail.listeners.pointermove({clientX:100,pointerId:1,preventDefault(){}});assert.equal(rail.scrollLeft,940);rail.listeners.pointerup({pointerId:1});rail.listeners.click({preventDefault(){prevented=true},stopPropagation(){stopped=true}});assert.ok(prevented&&stopped);
assert.equal(run('plants.length'),42);assert.equal(run('pots.length'),14);
assert.ok(run("plants.every(p=>pots.every(pot=>!(/NaN|undefined/.test(composition({plantId:p.id,potId:pot.id,transform:{x:.5,y:.6,scale:1}})))))"));
assert.match(run("composition({plantId:'p10',potId:'pot0',transform:{x:.5,y:.6,scale:1}})"),/lucky-cutout/);
assert.match(run("composition({plantId:'p06',potId:'pot0',transform:{x:.5,y:.6,scale:1}})"),/overhang/);
click('save-combo');assert.equal(hash,'#/success');run('render()');assert.match(elem('#app').innerHTML,/small-return/);
// All-plant filters narrow the list without changing the placed plant or pot.
hash='#/visualizer/p18';run('render()');const placed=run('viz.plantId'),chosenPot=run('viz.potId');click('viz-filter:types:식충식물');assert.deepEqual(Array.from(run('filterPlants(plants,state.visualizerFilters).map(p=>p.id)')),['p36','p38']);click('viz-filter:size:3');assert.deepEqual(Array.from(run('filterPlants(plants,state.visualizerFilters).map(p=>p.id)')),['p38']);assert.equal(run('viz.plantId'),placed);assert.equal(run('viz.potId'),chosenPot);click('tab:pots');click('tab:plants');assert.ok(elem('#app').innerHTML.includes('식충식물'));handlers.input({target:{id:'viz-search',value:'없는식물'}});assert.match(elem('#visualizer-results').innerHTML,/조건에 맞는 식물이 없어요/);click('viz-filters-clear');assert.equal(run('filterPlants(plants,state.visualizerFilters).length'),42);hash='#/explore';run('render()');click('filter:types:열매식물');assert.ok(run("filtered().every(p=>p.types.includes('열매식물'))"));assert.equal(run('state.visualizerFilters.types.length'),0);click('filters-clear');
click('recommend');run('render()');assert.equal(hash,'#/auth');hash='#/signup';run('render()');elem('#username').value='초록집';elem('#agree-service').checked=false;elem('#agree-storage').checked=true;run('startSignup()');assert.equal(run('state.signupDraft'),null);elem('#agree-service').checked=true;run('startSignup()');run('render()');assert.equal(hash,'#/profile/care');assert.equal(run('member()'),false);
click('answer:1');click('care-exit');run('render()');assert.equal(run('state.account'),null);assert.equal(run('state.careDraft.experience'),1);click('resume-signup');run('render()');assert.equal(run('question'),1);
for(const answer of [0,0,1]){click('answer:'+answer);click('question-next');run('render()');}assert.equal(hash,'#/');assert.equal(run('state.account.username'),'초록집');assert.equal(run('member()'),true);assert.equal(run('state.careProfile.size'),1);assert.equal(run('state.spaces.length'),1);
click('recommend');run('render()');assert.equal(hash,'#/recommendations');assert.match(elem('#app').innerHTML,/내 공간에 놓아보기/);
click('care-edit');run('render()');click('answer:2');click('care-exit');run('render()');assert.equal(run('state.careProfile.experience'),1);
click('logout');run('render()');assert.equal(run('member()'),false);assert.equal(run("match(find('p03'))"),null);elem('#login-id').value='wrong';run('signIn()');assert.equal(run('member()'),false);elem('#login-id').value='초록집';run('signIn()');run('render()');assert.equal(run('member()'),true);
const firstId=run('state.activeSpaceId');run("state.savedCombinations=[{id:'first',spaceId:state.activeSpaceId,plantId:'p03',potId:'pot0',transform:{x:.2,y:.7,scale:1}}]");
for(let i=0;i<3;i++){click('new-space');run('render()');click('type:베란다');click('setup-next');await run("savePhoto('data:image/jpeg;base64,/9j/',null)");}assert.equal(run('state.spaces.length'),4);click('new-space');assert.equal(run('state.spaces.length'),4);
const fourth=run('state.activeSpaceId');run("state.savedCombinations.push({id:'last',spaceId:state.activeSpaceId,plantId:'p04',potId:'pot1',transform:{x:.8,y:.7,scale:1}})");await run("savePhoto('data:image/jpeg;base64,/9j/NEW',null)");assert.equal(run("state.savedCombinations.find(c=>c.id==='first').transform.x"),.2);assert.equal(run("state.savedCombinations.find(c=>c.id==='last').transform.x"),.5);
click('open-combo:first');run('render()');assert.equal(run('state.activeSpaceId'),firstId);click('viz-pot:pot2');click('save-combo');assert.equal(run("state.savedCombinations.find(c=>c.id==='first').potId"),'pot2');assert.equal(run('state.savedCombinations.length'),2);
for(const route of ['/','/space/photo','/space/result','/profile/care','/recommendations','/explore','/plants/p03','/compare','/visualizer/p03','/saved','/my-page','/success']){hash='#'+route;run('render()');assert.ok(elem('#app').innerHTML.includes('<main>'));assert.ok(!/프로토타입|모의 분석|예시 분석|데모 이미지/.test(elem('#app').innerHTML),route);}
// Roll back failed photo writes without changing the current image or placements.
const before=run('JSON.stringify(state)');ctx.localStorage.setItem=()=>{throw Error('QuotaExceededError')};await run("savePhoto('new photo',null)");assert.equal(run('JSON.stringify(state)'),before);
console.log('PASS: intro/guest placement, consent gates, signup completion/cancel/resume, local ID login/logout, score gating, 4 spaces, scoped saved combinations, render routes and quota rollback');})();
